spring:
  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/menu_service_db
    username: postgres
    password: Chamath@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        format_sql: true

  # GCP Storage Configuration (for menu item images)
  cloud:
    gcp:
      project-id: mineral-balm-491310-u1
      storage:
        bucket: cafeteria-system-menu-images-bucket

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
